#!/bin/bash
# Update packages 
apt-get update
# Ensure Puppet bin is captured in environment
export PATH=/opt/puppetlabs/bin:$PATH
# Setup git and apache2
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
# Cleanup and recreate the working directory
puppet resource file /tmp/4595427u/research ensure=absent force=true
puppet resource file /tmp/4595427u ensure=directory
puppet resource file /tmp/4595427u/research ensure=directory
# Deploy new updates
cd /tmp/4595427u/research
git clone https://github.com/chinteck847/4595427u_op_repo.git
cp -p /tmp/4595427u/research/4595427u_op_repo/4595427u_index.html /var/www/html/index.html
